### ISSUE TITLE
owner authentication

### ISSUE THREAD

**Issue by bsdlp** [anthonynguyen/pugbot_ng#21]
it would be great if owners didn't have to use a password string every time when running a command. Especially since the bot messages the user a password already, which means it trusts that username.

So either:

1) owners are stored with full username/ircnick/hostmask
2) based on userserv/nickserv/whatever account

**Comment by anthonynguyen** [comment]
I added the login command [1] so that people can use privileged commands without the password every time, and I also logged in owners automatically [2].

[1] b262a725
[2] 224a0684

**Comment by anthonynguyen** [comment]
And yeah, we should store the owners in a more secure way.

**Comment by bsdlp** [comment]
well it's not really the storing part i care about, it's the fact that the bot just messages whoever is named "herpaderp" at the time that the bot starts and assumes authentication but then still requires a password. This issue is 0.3333 parts security, 4 parts "we can do better"

**Comment by anthonynguyen** [comment]
@fly, do you think hostmask-based authentication would be better?

**Comment by bsdlp** [comment]
is it easy to get the "logged in as <username>" jawn for Q? that's probably the best way

**Comment by anthonynguyen** [comment]
I've done it by hostmask.
